template = "https://github.com/giellalt/template-lang-und"
rev_id = 308
template_sha = "ec3d8dc80df568320da1b4f5034d7f589ea9f666"

[replacements]
__GLOTTOLOG_ID__ = "cebu1242"
__REPO__ = "lang-ceb"
__UND2C__ = "ceb"
__UNDEFINED__ = "Cebuano"
__UND__ = "ceb"
___LICENSE__ = "LGPLv3"
