template = "https://github.com/giellalt/template-lang-und"
rev_id = 312
template_sha = "aaa43738ed413bb95e9bd39f5489b35bab88cc4b"

[replacements]
__GLOTTOLOG_ID__ = "cebu1242"
__REPO__ = "lang-ceb"
__UND2C__ = "ceb"
__UNDEFINED__ = "Cebuano"
__UND__ = "ceb"
___LICENSE__ = "LGPLv3"
