template = "https://github.com/giellalt/template-lang-und"
rev_id = 304
template_sha = "6db72d2e1012558dae41ff0c67944d6ae89b182a"

[replacements]
__GLOTTOLOG_ID__ = "cebu1242"
__REPO__ = "lang-ceb"
__UND2C__ = "ceb"
__UNDEFINED__ = "Cebuano"
__UND__ = "ceb"
___LICENSE__ = "LGPLv3"
